---
title: ""
author: ""
output: html_document
---


## Control Structures in R {.tabset}

### If/Else statements

`if` and `else`: testing a condition and acting on it

`for`: execute a loop for a fixed number of times.


```{r if/else, message=FALSE, warning=FALSE}
if(condition) {
        ## do something
} 
## Continue with rest of code



if(condition) {
        ## do something
} else {
        ## do something else
}


if(condition1) {
        ## do something
} else if(condition2)  {
        ## do something different
} else {
        ## do something different
}
```


### For Loops
```{r for, message=FALSE, warning=FALSE}
for (item in items){
  # do something
}


# We can integrate For loops with if/else statements

for (item in items){
  if (condition){
    # do something
  } else {
  # do something else
  }
}


```


### Examples and Exercises
```{r control structures examples}
# If/else

age <- 103

if (age < 18) {
  category <- "Minor"
} else if (age >= 18 & age < 65) {
  category <- "Adult"
} else {
  category <- "Senior"
}

print(paste("Person is a/an", category)) # print a message





# for loops
# Let's calculate the square of each number from 1:10

for (x in 1:10) {
  a <- x ^ 2 
  print(a)
}



dice <- 1:6

for(x in dice) {
  if (x == 6) {
    print(paste("The dice number is", x, "yayy!"))
  } else {
    print(paste("The dice number is", x, "better luck next time"))
  }
}




# Exercises
# 1. What'll be the output

grades <- 85
income <- 25000

if (grades >= 80) {
  if (income <= 30000) {
    print("Congratulations, you are eligible for a scholarship!")
  } else {
    print("Sorry, your income is too high to qualify for a scholarship.")
  }
} else {
  print("Sorry, your grades are too low to qualify for a scholarship.")
}


# 2. What'll be the output

sum <- 0
for (i in 1:10) {
  sum <- sum + i
}

print(sum)

```


